sudo: required
services:
    - docker
before_install:
    - docker build -t aam300/fib-cal -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aam300/fib-cal npm run test
after_success:
    - docker build -t aam300/multi-client ./client 
    - docker build -t aam300/multi-nginx ./nginx
    - docker build -t aam300/multi-server ./server
    - docker build -t aam300/multi-worker ./worker
    # pushing image to docker hub
    # loging in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push aam300/multi-client
    - docker push aam300/multi-nginx
    - docker push aam300/multi-server
    - docker push aam300/multi-worker
